# -------------------=-=------------------- #
#         Author: DanielZinh#7616
#    https://github.com/LaivyTLife/DataAPI
# -------------------=-=------------------- #

check-updates: true

# Values more than 600 seconds is not recommended.
AutoSaver: 600 # seconds