# -------------------=-=------------------- #
#         Author: DanielZinh#7616
#    https://github.com/ItsLaivy/DataAPI
# -------------------=-=------------------- #

check-updates: true

# Values more than 600 seconds are not recommended.
auto saver time: 600 # seconds
auto saver message: true

# Messages
variable messages: false
table messages: false
database messages: false