name: DataAPI
version: 4.0
main: codes.laivy.dataapi.main.DataAPI
author: DanielZinh#7616
description: "Player's variable saving system."
api-version: 1.13

website: "https://github.com/ItsLaivy/DataAPI"

load: POSTWORLD

commands:
  dataapi:
    description: "General plugin' command"
    aliasess: lvdataapi

permissions:
  lvdataapi.command.use:
    description: "Access to the general command."
    default: op